# Custom Language File for Launcher Customizer

[ejs.app]
title = "Ren Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/RENKUN0105/RenLauncher"
mediaTwitterURL = "https://x.com/RENKUN0105
mediaInstagramURL = "https://www.instagram.com/renkun0105"
mediaYouTubeURL = "https://www.youtube.com/@RENKUN0105"
mediaDiscordURL = "https://discord.gg/XXJjssSv4N"

[ejs.settings]
sourceGithubLink = "https://github.com/RENKUN0105/RenLauncher"
supportLink = "https://github.com/RENKUN0105/RenLauncher/issues"

[ejs.welcome]
welcomeHeader = "ようこそ、RENランチャーへ"
welcomeDescription = "誰でもModが導入できる、そんなランチャーです。"
welcomeDescCTA = "数クリックでRENサーバーへ参加する準備が整います。"
